### DISCUSSION TITLE
jobs.<job_id>.needs

### DISCUSSION THREAD

**Discussion by mkungla** [mkungla/github-cicd#107] [Workflow syntax examples]
Identifies any jobs that must complete successfully before this job will run. It can be a string or array of strings. If a job fails, all jobs that need it are skipped unless the jobs use a conditional expression that causes the job to continue.

**Comment by mkungla** [comment]
Example: **run D after `succes` || `skipped` dependency**

```yaml
jobs:
  A:
    runs-on: ubuntu-latest
    steps:
      - run: echo "success always"
  B:
    runs-on: ubuntu-latest
    if: false
    steps:
      - run: echo "this will never run"
  C:
    runs-on: ubuntu-latest
    if: false
    steps:
      - run: |
          exho "here to fail"
          exit 1
  D:
    runs-on: ubuntu-latest
    needs: [A, B, C]
    if: |
      always() &&
      !contains(needs.*.result, 'failure') &&
      !contains(needs.*.result, 'cancelled')
    steps:
      - run: echo "${{ toJSON(needs) }}"
```
