### DISCUSSION TITLE
issues.yml

### DISCUSSION THREAD

**Discussion by mkungla** [mkungla/github-cicd#11] [Workflow Files]
**workflow** [issues.yml](.github/workflows/issues.yml) tests different scenarios with GitHub issues

**Comment by mkungla** [comment]
**issue_comment**

Runs your workflow anytime the issue_comment event occurs. More than one activity type triggers this event. For information about the REST API, see
https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#issue_comment

```yaml
on:
  issue_comment:
    types:
      - created
      - deleted
      - edited
```

```yaml
if: github.event_name === 'issue_comment' && !github.event.issue.pull_request
```
