### DISCUSSION TITLE
on

### DISCUSSION THREAD

**Discussion by mkungla** [mkungla/github-cicd#119] [Workflow syntax examples]
[on](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#name)

Required. The name of the GitHub event that triggers the workflow. You can provide a single event string, array of events, array of event types, or an event configuration map that schedules a workflow or restricts the execution of a workflow to specific files, tags, or branch changes. For a list of available events, see "Events that trigger workflows."

**[Example: Using a single event*](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-using-a-single-event)**
```yaml
# Triggered when code is pushed to any branch in a repository
on: push
```

**[Example: Using a list of events](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-using-a-list-of-events)**
```yaml
# Triggers the workflow on push or pull request events
on: [push, pull_request]
```

**Example: Using multiple events with activity types or configuration**

If you need to specify activity types or configuration for an event, you must configure each event separately. You must append a colon (:) to all events, including events without configuration.

```yaml
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Also trigger on page_build, as well as release created events
  page_build:
  release:
    types: # This configuration does not affect the page_build event above
      - created
```
| **event** |  |
| --- | --- |
| on.check_run | |
| on.check_suite | |
| on.create | |
| on.delete | |
| on.deployment | |
| on.deployment_status | |
| on.discussion | |
| on.discussion_comment | |
| on.fork | |
| on.gollum | |
| on.issue_comment | |
| on.issues | |
| on.label | |
| on.check_run | |
| on.milestone | |
| on.page_build | |
| on.project | |
| on.project_card | |
| on.project_column | |
| on.public | |
| on.pull_request | |
| on.pull_request_review | |
| on.pull_request_review_comment | |
| on.pull_request_target | |
| on.push | |
| on.registry_package | |
| on.release | |
| on.status | |
| on.watch | |
| on.workflow_run | |
| on.repository_dispatch | |
| on.workflow_dispatch | |
| on.schedule | |
